### ISSUE TITLE
migration to saberjs successfully :D

### ISSUE THREAD

**Issue by chawyehsu** [egoist/awesome-saber#1]
[www.h404bi.com](https://www.h404bi.com) ([source](https://github.com/h404bi/www.h404bi.com))

Special moments: [migration merged](https://github.com/h404bi/www.h404bi.com/pull/4), [ci build passing](https://travis-ci.org/h404bi/www.h404bi.com/builds/513808931?utm_source=github_status&utm_medium=notification), [auto deployment works](https://github.com/h404bi/www.h404bi.com/commit/644e085e8e4a8abc048cdb798a0126b476e6bdc3).

**Comment by egoist** [comment]
You can send PR to add your blog [here](https://github.com/egoist/awesome-saber#blogs) 👀

btw why not deploy to Netlify?
